package pers.jc.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

public abstract class Transaction {
	private Connection connection;
	private ArrayList<PreparedStatement> preparedStatements = new ArrayList<>();
	private ArrayList<ResultSet> resultSets = new ArrayList<>();
	
	public Transaction() {
		try {
			connection = Access.getConnection();
			connection.setAutoCommit(false);
			run();
			connection.commit();
		} catch (Exception e) {
			try {
				connection.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
			e.printStackTrace();
		} finally {
			for (ResultSet resultSet : resultSets) {
				if (resultSet != null) {
					try {
						resultSet.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
			for (PreparedStatement preparedStatement : preparedStatements) {
				if (preparedStatement != null) {
					try {
						preparedStatement.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
			if (connection != null) {
				try {
					connection.setAutoCommit(true);
				} catch (Exception e) {
					Access.closeConnection(connection);
					connection = null;
					e.printStackTrace();
				} finally {
					Access.pool.add(connection);
				}
			}
		}
	}
	
	public abstract void run() throws Exception;
	
	public int insert(SQL sql) throws Exception {
		PreparedStatement preparedStatement = getPreparedStatement(sql, Statement.NO_GENERATED_KEYS);
		return preparedStatement.executeUpdate();
	}
	
	public int insertAndReturnKey(SQL sql) throws Exception {
		PreparedStatement preparedStatement = getPreparedStatement(sql, Statement.RETURN_GENERATED_KEYS);
		int key = 0;
		int count = preparedStatement.executeUpdate();
		if (count > 0) {
			ResultSet resultSet = preparedStatement.getGeneratedKeys();
			resultSets.add(resultSet);
			resultSet.next();
			key = resultSet.getInt(1);
		}
		return key;
	}
	
	public int update(SQL sql) throws Exception {
		PreparedStatement preparedStatement = getPreparedStatement(sql, Statement.NO_GENERATED_KEYS);
		return preparedStatement.executeUpdate();
	}
	
	public int delete(SQL sql) throws Exception {
		PreparedStatement preparedStatement = getPreparedStatement(sql, Statement.NO_GENERATED_KEYS);
		return preparedStatement.executeUpdate();
	}
	
	private PreparedStatement getPreparedStatement(SQL sql, int autoGeneratedKeys) throws Exception {
		PreparedStatement preparedStatement = connection.prepareStatement(sql.toString(), autoGeneratedKeys);
		preparedStatements.add(preparedStatement);
		return preparedStatement;
	}
}
